[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.gd",
    "php82Extensions.zip",
    "php82Extensions.pdo_sqlite",
    "php82Extensions.bcmath",
    "php82Extensions.fileinfo",
    "php82Extensions.mbstring",
    "php82Extensions.openssl",
    "php82Extensions.tokenizer",
    "php82Extensions.xml",
    "php82Extensions.dom",
    "php82Extensions.curl",
    "nodejs_20"
]

[phases.build]
cmds = [
    "npm install && npm run build",
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs"
]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
